name: moinak05_web_dev_dashboard
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  firebase_core: ^2.16.0
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  flutter_riverpod: ^2.3.10
  image_picker: ^1.0.4
  path: ^1.8.3
  url_launcher: ^6.1.14
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  flutter_html: ^3.0.0-beta.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  choice: ^2.0.0
  enum_to_string: ^2.0.1
  animated_text_kit: ^4.2.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_expandable_fab: ^2.0.0
  path_provider: ^2.1.1
  just_audio: ^0.9.35
  audio_video_progress_bar: ^2.0.0
  rxdart: ^0.27.7
  just_audio_background: ^0.0.1-beta.10
  local_auth: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "assets/icon/background.png"
  adaptive_icon_foreground: "assets/icon/foreground.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/icon/
    - assets/language/
    - assets/music/
    - assets/music/cover/
    - .env

